import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import dotenv from "dotenv";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, "..");
const envPath = path.join(projectRoot, ".env");

export function loadEnvFromFile() {
  if (!fs.existsSync(envPath)) {
    return { envObject: {}, exists: false };
  }

  const raw = fs.readFileSync(envPath, "utf8");
  if (!raw.trim()) {
    return { envObject: {}, exists: true };
  }

  const parsed = dotenv.parse(raw);
  return { envObject: parsed, exists: true };
}

function makeBackupName() {
  const now = new Date();
  const yyyy = now.getFullYear().toString();
  const mm = String(now.getMonth() + 1).padStart(2, "0");
  const dd = String(now.getDate()).padStart(2, "0");
  const hh = String(now.getHours()).padStart(2, "0");
  const min = String(now.getMinutes()).padStart(2, "0");
  const ss = String(now.getSeconds()).padStart(2, "0");
  return `.env.backup-${yyyy}${mm}${dd}-${hh}${min}${ss}`;
}

export function saveEnvAtomic(newEnvObject) {
  const lines = [
    "# ghostAutoPublish configuration",
    "# Generated by the setup/admin CLI. Do not commit this file to git.",
    ""
  ];

  Object.entries(newEnvObject).forEach(([key, value]) => {
    if (value === undefined || value === null || value === "") return;
    lines.push(`${key}=${String(value)}`);
  });

  const content = `${lines.join("\n")}\n`;

  const tmpPath = `${envPath}.new`;
  let backupPath = "";

  try {
    if (fs.existsSync(envPath)) {
      backupPath = path.join(projectRoot, makeBackupName());
      fs.copyFileSync(envPath, backupPath);
    }

    fs.writeFileSync(tmpPath, content, "utf8");
    fs.renameSync(tmpPath, envPath);
  } catch (err) {
    if (fs.existsSync(tmpPath)) {
      fs.unlinkSync(tmpPath);
    }
    if (backupPath && fs.existsSync(backupPath) && !fs.existsSync(envPath)) {
      fs.copyFileSync(backupPath, envPath);
    }
    throw err;
  }
}

export function listEnvBackups() {
  const files = fs.readdirSync(projectRoot);
  return files
    .filter((name) => name.startsWith(".env.backup-"))
    .map((name) => ({
      name,
      path: path.join(projectRoot, name)
    }));
}

